version: '3'

services:
  postgres:
    image: library/postgres:9.6-alpine
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=guest
    networks:
      - development

networks:
  development:
    driver: bridge